name: agrogenicprl
description: A new IoT based Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^3.9.0
  firebase_core: ^1.22.0
  fluttertoast: ^8.0.9
  cloud_firestore: ^3.4.8
  get: ^4.6.5
  sleek_circular_slider: ^2.0.1
  flutter_switch: ^0.3.2
  flutter_icons: ^1.1.0
  fl_chart: ^0.55.1
  firebase_database: ^9.1.4
  kdgaugeview: ^1.0.4
  chart_sparkline: ^1.0.11

  flare_flutter: ^3.0.2
  shared_preferences: ^2.0.15
  syncfusion_flutter_gauges: ^20.3.47
  http: ^0.13.5
  flutter_svg: ^1.1.5
  font_awesome_flutter: ^10.2.1
  percent_indicator: ^4.2.2
  d_chart: ^0.0.4
  flutter_staggered_animations: ^1.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  assets_audio_player: ^3.0.5

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
     - assets/startup.png
     - assets/agri.png
     - assets/logo.png
     - assets/agrogenic.png
     - assets/pest.png
     - assets/fertilizer.png
     - assets/temp.jpg
     - assets/pestc.jpg
     - assets/light.png
     - assets/profile.png
     - assets/guide.png
     - assets/plantheightm.png
     - assets/fertiscrnmfile.png
     - assets/pestrepellent.PNG
     - assets/airventiscreenms.PNG
     - assets/images/avent.png
     - assets/sonar-ping-sound-effect.mp3
     - assets/airventiht.jpg
     - assets/temmi.png
     - assets/hummi.png
     - assets/smoki.png
     - assets/lpgi.png
     - assets/power.png



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

